config/routes.rb
 Rails.application.routes.draw do
  devise_for :admins
  resources :posts 
  resources :analyses

  root "pages#index"
  get '/about', to: 'pages#about'

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]


end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/models/analysis.rb
class Analysis < ActiveRecord::Base

has_attached_file :image, :styles => { :inpost => "778x514#", :header  => "1900x800#" }
# , :default_url => "/images/:style/missing.png"
                      # :storage => :s3,
                      # :s3_credentials => {
                      # :bucket => ENV['AWS_BUCKET'],
                      # :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                      # :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                      # },
                      # :path => ":class/:id/:basename_:style.:extension",
                      # :s3_host_name => "s3-ap-southeast-1.amazonaws.com"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Barecoin Enquiry",
      :to => "andreas@bbdlabs.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :admin

has_attached_file :image, :styles => { :inpost => "778x514#", :header  => "1900x800#" }
# , :default_url => "/images/:style/missing.png"
                      # :storage => :s3,
                      # :s3_credentials => {
                      # :bucket => ENV['AWS_BUCKET'],
                      # :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                      # :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                      # },
                      # :path => ":class/:id/:basename_:style.:extension",
                      # :s3_host_name => "s3-ap-southeast-1.amazonaws.com"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController

   before_action :find_analysis, only: [:show, :edit, :update, :destroy]
  def index
   @analyses = Analysis.all.order('created_at DESC').paginate(page: params[:page], per_page: 2)
   set_meta_tags title: 'News & Analysis',
              description: 'Fundamental and Technical Analysis about Bitcoin and Etheruem',
              keywords: 'Bitcoin, Ethereum, Ether, Technical, Fundamental, Analysis'
 
  end

  def new
    @analysis = Analysis.new

    set_meta_tags noindex: true
    set_meta_tags noindex: 'googlebot'
  end

  def create
    @analysis = Analysis.new analysis_params

    if @analysis.save
      redirect_to @analysis, notice: "Analysis done brah!!"
    else
      render 'new', notice: "Unsuccesfull brah!!"
    end

  end

  def show
  end

  def edit
    set_meta_tags noindex: true
    set_meta_tags noindex: 'googlebot'
  end

  def update
    if @analysis.update analysis_params
      redirect_to @analysis, notice: "Article is updated. Bleep Blop"
    else 
      render 'edit'
    end
  end 

  def destroy
    @analysis.destroy
    redirect_to analyses_path

    set_meta_tags noindex: true
    set_meta_tags noindex: 'googlebot'
  end


  private
    
    def analysis_params
      params.require(:analysis).permit(:title, :content, :subtitle, :image)
    end 

    def find_analysis
      @analysis = Analysis.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  def index
   @posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 5)
   set_meta_tags title: 'Blog',
              description: 'News, Interviews, Posts about Cryptocurrencies - namely Bitcoin and Etheruem plus the Blockchain',
              keywords: 'Bitcoin, Ethereum, Ether, Blockchain, News'
  end

  def new
    @post = current_admin.posts.build
    set_meta_tags noindex: true
    set_meta_tags noindex: 'googlebot'

  end

  def create
    @post = current_admin.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: "Post done brah!!"
    else
      render 'new', notice: "Unsuccesfull brah!!"
    end

    set_meta_tags noindex: true
    set_meta_tags noindex: 'googlebot'

  end

  def show
  end

  def edit
    set_meta_tags noindex: true
    set_meta_tags noindex: 'googlebot'
  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "Article is updated. Bleep Blop"
    else 
      render 'edit'
    end
  end 

  def destroy
    @post.destroy
    redirect_to posts_path

    set_meta_tags noindex: true
    set_meta_tags noindex: 'googlebot'
  end


  private
    
    def post_params
      params.require(:post).permit(:title, :content, :subtitle, :image)
    end 

    def find_post
      @post = Post.find(params[:id])
    end


end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/analyses/_form.html.erb
 
<div class="container">

       <%= form_for @analysis, html: { multipart: true } do |f| %>
        <% if @analysis.errors.any? %>
          <div id="errors">
            <h2><%= pluralize(@analysis.errors.count, "error") %> prevented this analysis from saving:</h2>
            <ul>
              <% @analysis.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>


        <%= f.label :title %><br>
        <%= f.text_field :title, class: "form-control" %>
        
        <br>
        <br>
        
        <%= f.label :subtitle %><br>
        <%= f.text_field :subtitle, class: "form-control" %>
        
        <br>
        <br>

        <%= f.label :content %><br>
        <%= f.text_area :content, class: "form-control", rows: "8" %>
        
        <br>
        <br>

        <%= f.label :image %><br>
        <%= f.file_field :image , class: "form-control"%>

        <br>
        <br>

        <%= f.submit "Publish", :class=> "btn btn-default" %>
      <% end %>

</div>

app/views/analyses/edit.html.erb
<h1> Edit Analysis! </h1>

<%= render 'form' %>

app/views/analyses/index.html.erb
<!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header index-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Barecoin</h1>
                        <hr class="small">
                        <span class="subheading"><%= title "Analysis" %> for Crypto Punters </span>
                    </div>
                </div>
            </div>
        </div>
    </header>


<!-- Main Content -->
  <div class="container">
    <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <% @analyses.each do |analysis| %>
                <div class="post-preview">
                    <!-- <a href="post.html"> -->
                        <h2 class="post-title">
                            <%= link_to "#{analysis.title}", analysis_path(analysis) %>
                        </h2>
                        <h3 class="post-subtitle">
                            <%= analysis.subtitle %>
                        </h3>
                    <!-- </a> -->
                    <p class="post-meta">Published <%= analysis.created_at.strftime('%d %B, %Y') %></p>
                </div>
                <hr>
                <% end %>

                <%= will_paginate @posts %>
                
               
                <!-- Pager -->
                <!-- <ul class="pager">
                    <li class="next">
                        <a href="#">Older Analyses &rarr;</a>
                    </li>
                </ul> -->
             </div>   
    </div>
  </div>
  

  <hr>

app/views/analyses/new.html.erb
<header class="intro-header index-bg">
  <div class="container">
  <h1 class="white-title"> New Analysis </h1>
  </div>
</header>



<%= render 'form' %>

app/views/analyses/show.html.erb
 <header class="intro-header post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1><%= @analysis.title %></h1>
                        <h2 class="subheading"><%= @analysis.subtitle %></h2>
                        <span class="meta">Published <%= @analysis.created_at.strftime('%d %B, %Y') %> </span>
                    </div>
                </div>
            </div>
        </div>
    </header>

<!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <%= image_tag @analysis.image.url(:inpost) %>
                    <br>
                    <br>
                    <%= @analysis.content %>

                    
                </div>
            </div>
        </div>
    </article>

    <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                    <p> Share the story! </p>
                        <li>
                            <a href="javascript:window.open('http://twitter.com/share?text=<%= @analysis.title %> by @agweiler - &amp;url=<%= url_for([@analysis, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@analysis, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:window.open('http://plus.google.com/share.php?u=<%= url_for([@analysis, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    <hr>

    <% if admin_signed_in? %>

    <%= link_to "Edit", edit_analysis_path(@analysis) %>
    <%= link_to "Delete", analysis_path(@analysis), method: :delete, data: { confirm: "Sure you want to?"} %>

    <% end %>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header contact-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1><%= title 'Contact' %> Me</h1>
                        <hr class="small">
                        <span class="subheading">Have feedback or an article to contribute?</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>I'd be Happy to hear from you. Fill out the form below and I will try to get back to you within 24 hours.</p>
                <%= simple_form_for @contact, :html => {:class => '' } do |f| %>

                <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        <%= f.input :name, placeholder: "Name*", :required => true, class: "form-control" %>
                        </div>
                    </div>

                <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        <%= f.input :email, placeholder: "Email*",:required => true, class: "form-control" %>
                        </div>
                    </div>

                <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                        <%= f.input :message, placeholder: "Message*", :as => :text, rows: 5, :required => true, class: "form-control" %>
                        </div>
                    </div>
                    <br>

                <div class= "hidden">
                  <%= f.input :nickname, :hint => 'Leave this field blank!' %>
                </div>

                <div>
                  </br>

                  <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                        <%= f.button :submit, 'Send', :class=> "btn btn-default" %>
                        </div>
                    </div>
                  </div>
                </div>

                <% end %>



               
                    
                
            </div>
        </div>
    </div>

    <hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barecoin - Cryptocurrency News and Analysis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= display_meta_tags site: 'Barecoin - Cryptocurrency Trading News and Analysis' %>
  <%= favicon_link_tag 'barecoin_fav.ico' %>


  <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

</head>
<body>

<!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">BARECOIN</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/analyses">Analysis</a>
                    </li>
                    <li>
                        <a href="/posts">Blog</a>
                    </li>
                    <li>
                        <a href="/about">About</a>
                    </li>
                    <li>
                        <a href="/contacts">Contact</a>
                    </li>
                    <% if admin_signed_in? %>
                    <li>
                        <%= link_to('Logout', destroy_admin_session_path, :method => :delete, class: 'logout') %>        
                    </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->

    <!-- Notices -->

    <!-- <% if notice  %>       
      <div class="alert alert-success alert-dismissable" style="z-index: 999999">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
          ×</button>
          <%= notice %>
      </div>
    <% end %> -->

    <!-- Alerts -->

    <!-- <% if alert %>

      <div class="alert alert-danger alert-dismissable">
        <span class="glyphicon glyphicon-certificate"></span>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        ×</button>
        <%= alert %>
      </div>
    <% end %> -->

<%= yield %>


<!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Barecoin Ltd. 2016</p>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

app/views/pages/about.html.erb
<!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header about-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1><%= title "About" %></h1>
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
            </div>
        </div>
    </div>

    <hr>

app/views/pages/index.html.erb
<!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header home-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Barecoin</h1>
                        <hr class="small">
                        <span class="subheading"> <%= title 'New Media' %> for Crypto Punters</span>
                    </div>
                </div>
            </div>
        </div>
    </header>


<!-- Main Content -->
  <div class="container">
    <div class="row">
            
    </div>
  </div>
  

  <hr>

app/views/posts/_form.html.erb
 
<div class="container">

   <%= form_for @post, html: { multipart: true } do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
    
    <br>
    <br>
    
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle, class: "form-control" %>
    
    <br>
    <br>

    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control", rows: "8" %>
    
    <br>
    <br>

    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>

    <br>
    <br>

    <%= f.submit "Publish", :class=> "btn btn-default" %>
  <% end %>

</div>

app/views/posts/edit.html.erb
<h1> Edit Post! </h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header index-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Barecoin</h1>
                        <hr class="small">
                        <span class="subheading">The Blog for Crypto Punters</span>
                    </div>
                </div>
            </div>
        </div>
    </header>


<!-- Main Content -->
  <div class="container">
    <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <% @posts.each do |post| %>
                <div class="post-preview">
                    <!-- <a href="post.html"> -->
                        <h2 class="post-title">
                            <%= link_to "#{post.title}", post_path(post) %>
                        </h2>
                        <h3 class="post-subtitle">
                            <%= post.subtitle %>
                        </h3>
                    <!-- </a> -->
                    <p class="post-meta">Published <%= post.created_at.strftime('%d %B, %Y') %></p>
                </div>
                <hr>
                <% end %>
                
                <%= will_paginate @posts %>
               
                <!-- Pager -->
                <!-- <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul> -->
             </div>   
    </div>
  </div>
  

  <hr>

app/views/posts/new.html.erb
<header class="intro-header index-bg">
  <div class="container">
  <h1 class="white-title"> New Post </h1>
  </div>
</header>

<%= render 'form' %>

app/views/posts/show.html.erb
    <header class="intro-header post-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1><%= @post.title %></h1>
                        <h2 class="subheading"><%= @post.subtitle %></h2>
                        <span class="meta">Published <%= @post.created_at.strftime('%d %B, %Y') %> </span>
                    </div>
                </div>
            </div>
        </div>
    </header>

<!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <%= image_tag @post.image.url(:inpost) %>
                <br>
                <br>
                <%= @post.content %>
 
                    
                </div>
            </div>
        </div>
    </article>

    <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                    <p> Share the story! </p>
                        <li>
                            <a href="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @agweiler - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:window.open('http://www.facebook.com/sharer/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:window.open('http://plus.google.com/share.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    <hr>

<% if admin_signed_in? %>
    <%= link_to "Edit", edit_post_path(@post) %>
    <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Sure you want to?"} %>
<% end %>